title: "Kode Krew"
description: >- # this means to ignore newlines until "baseurl:"
  Kode Krew is a guild for the LHD Build
  week-long hackathon during 2021! We are a
  group of friends learning and having fun!
baseurl: "/" 
url: "https://kode-krew.github.io/kode-krew/" 
github_username:  Kode-Krew

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
